apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: khaleel-app
  name: khaleel-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khaleel-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: khaleel-app
    spec:
      containers:
      - name: khaleel-container
        image: gcr.io/khaleelterraform/khaleel-image:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
